CREATE TABLE [dbo].[FacVisita] (
	[Id_Visita] [int] NOT NULL,
	[Id_Detalle_Visita] [int] NOT NULL,
	[SK_Paciente] [int] NOT NULL,
	[SK_Hospital] [int] NOT NULL,
	[SK_Medico] [int] NOT NULL,
	[Fecha_Visita] [date] NOT NULL,
	[Nombre_Servicio] VARCHAR(50) NULL,
	[Cargo_MHS] VARCHAR(50) NULL,
	[Precio_Ser_Hosp] [int] NULL,
	[Diagnostico] VARCHAR(200) NULL,
	[Es_Internacion] [int] NULL,
	[Id_Cama] [int]  NULL,
	[Cantidad_Dias] [int]  NULL,
	[Precio_Dias_Cama] [int] NULL,
	[Fecha_Ingreso] [date] NOT NULL,
	[Fecha_Salida] [date] NOT NULL,
	[Precio_MHS] [int] NULL,
	[es_Reconsulta] [int] NULL,
	[Id_Visita_inicial] [int] NOT NULL,
	[Precio_Visita] [float] NULL,
	[datos_adicionales] [float] NULL,
	[Tiempo_Key] [int] NOT NULL,
    CONSTRAINT [PK_Visita_FacVisita] PRIMARY KEY CLUSTERED ([Id_Visita],[Id_Detalle_Visita] ASC),
    CONSTRAINT [FK_Visita_Paciente] FOREIGN KEY ([SK_Paciente]) REFERENCES [dbo].[DimPaciente] ([SK_Paciente]),
	CONSTRAINT [FK_Visita_Hospital] FOREIGN KEY ([SK_Hospital]) REFERENCES [dbo].[DimHospital] ([SK_Hospital]),
	CONSTRAINT [FK_Visita_Medico] FOREIGN KEY ([SK_Medico]) REFERENCES [dbo].[DimMedico] ([SK_Medico]),
	CONSTRAINT [FK_Visita_Tiempo] FOREIGN KEY ([Tiempo_Key]) REFERENCES [dbo].[DimTiempo] ([Id_Tiempo])
);