CREATE TABLE [staging].[Visita]
(
	[Id_Visita] [int] NOT NULL,
	[Id_Detalle_Visita] [int] NOT NULL,
	[SK_Paciente] [int] NULL,
	[SK_Hospital] [int] NULL,
	[SK_Medico] [int] NULL,
	[Fecha_Visita] [date] NOT NULL,
	[Nombre_Servicio] VARCHAR(50) NULL,
	[Cargo_MHS] [varchar](50) NULL,
	[Precio_Ser_Hosp] [int] NULL,
	[Diagnostico] VARCHAR(200) NULL,
	[Es_Internacion] [int] NULL,
	[Id_Cama] [int]  NULL,
	[Cantidad_Dias] [int]  NULL,
	[Precio_Dias_Cama] [int] NULL,
	[Fecha_Ingreso] [date] NOT NULL,
	[Fecha_Salida] [date] NOT NULL,
	[Precio_MHS] [int] NULL,
	[es_Reconsulta] [int] NULL,
	[Id_Visita_inicial] [int] NOT NULL,
	[Precio_Visita] [float] NULL,
	[datos_adicionales] VARCHAR(1000) NULL,
	[Tiempo_Key] [int] NOT NULL,
)
